org: arroyodev
app: big3d
service: big3d

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: dev
  region: us-east-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
    binaryMediaTypes:
      - 'multipart/form-data'
  ecr:
    images:
      big3d-api:
        path: ./

functions:
  apiHandler:
    image:
      name: big3d-api
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
