org: arroyodev
app: big3d
service: big3d

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::${self:custom.prefix}*'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
    binaryMediaTypes:
      - 'multipart/form-data'
  s3:
    rendersBucket:
      name: ${self:custom.prefix}-renders
      accelerateConfiguration:
        AccelerationStatus: Enabled
  ecr:
    images:
      big3d-api:
        path: ./

custom:
  stage: ${opt:stage, self:provider.stage}
  prefix: big3d-api-${self:custom.stage}

functions:
  apiHandler:
    image:
      name: big3d-api
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
